version: '3'

services:
  app:
    build:
      context: ./app
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db

  db:
    build:
      context: ./mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'standings'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
